env:
  TZ: "Asia/Jakarta"
  LANG: "C.UTF-8"
  LC_ALL: "C"
  
  # Kernel
  DEVICE_CODENAME: "chime"
  BUILD_USER: "admin"
  BUILD_HOST: "mrtproject"
  KERNEL_SOURCE: "https://github.com/anggitmrt87/valeryn_xiaomi_sm6115.git"
  KERNEL_BRANCH: "staging"
  DEVICE_DEFCONFIG: "vendor/bengal-perf_defconfig vendor/xiaomi/sm6115.config vendor/xiaomi/lime.config"
  ANYKERNEL: "https://github.com/greenforce-project/AnyKernel3"
  
  # Telegram Encrypted Secrets
  TG_TOKEN: "ENCRYPTED[d9185ab32fea60b59b9caac7865c156001691d0c6c87c825c32a3db288ed566a8ac07cfe7ff445fb2c0e61f57c06b486]"
  TG_CHAT_ID: "ENCRYPTED[d1175d4be5c2ebcb2ce25c91ec7c71abeb738d22d563c4fc0afdb9f528c2d6997b98e29309468198038eb159cc709e91]"

  # Toolchain Configuration
  USE_CLANG: "aosp" # "aosp" or "greenforce"
  CLANG_ROOTDIR: "/tmp/cirrus-ci-build/clang"
  AOSP_CLANG_URL: "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/603a89415bbb04dff8bc577b95534479ec13fdc5/clang-r574158.tar.gz"
  GREENFORCE_CLANG_URL: "https://github.com/greenforce-project/greenforce_clang/releases/download/20251012/gf-clang-22.0.0git-20251012.tar.gz"

  # Kernel Build Configuration
  TYPE_IMAGE: "Image.gz"
  BUILD_DTBO: "false"

  # Kernel SU configuration
  KERNELSU: "false"
  KERNELSU_TYPE: "sukisu"
  KERNELSU_BRANCH: "susfs-main"
  KPM_PATCH: "false"
  KPM_VERSION: "0.12.0"

  # Build optimization
  BUILD_OPTIONS: "-j8"
  CCACHE: "true"
  CCACHE_DIR: "/tmp/ccache"
  CCACHE_MAXSIZE: "2G"
  CCACHE_COMPRESS: "true"
  
  # New: Enhanced logging and debugging
  DEBUG_MODE: "false"
  KEEP_BUILD_LOGS: "false"

task:
  name: "Kernel Build"
  timeout_in: 3h
  container:
    image: mhmmdfdlyas/dockerfile:k-ubuntu
    cpu: 8
    memory: 32G

  # Cache configuration
  ccache_cache:
    folder: /tmp/ccache
    fingerprint_script: 
      - cat .cirrus.yml
      - echo "$AOSP_CLANG_URL"
      - echo "$GREENFORCE_CLANG_URL"
      - echo "$DEVICE_DEFCONFIG"

  update_script:
    - apt-get update
    - apt-get install -y aria2 ccache libssl-dev ncurses-dev flex bison cpio xz-utils locales libtinfo5
    - echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen && /usr/sbin/locale-gen
    - ln -snf /usr/share/zoneinfo/"$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
    - apt-get clean

  setup_script:
    - mkdir -p /tmp/ccache
    - ccache -M $CCACHE_MAXSIZE
    - ccache -z

  sync_script:
    - chmod +x download.sh
    - ./download.sh

  build_script:
    - chmod +x build.sh
    - ./build.sh

  cleanup_script:
    - chmod +x done.sh
    - ./done.sh
