env:
  TZ: "Asia/Jakarta"
  LANG: "C.UTF-8"
  LC_ALL: "C"
  
  # Kernel
  DEVICE_CODENAME: "chime"
  BUILD_USER: "builder"
  BUILD_HOST: "mrtproject™"
  KERNEL_SOURCE: "ENCRYPTED[7c3d8848081f87af2cb9743d0620072dd1a9ad8d4b2d273ef8a4fd8cdffdb158ecc74c518979436d333b49a9cb92bfe2]"
  KERNEL_BRANCH: "android16"
  DEVICE_DEFCONFIG: "vendor/bengal-perf_defconfig"
  ANYKERNEL: "https://github.com/frstprjkt/AnyKernel3"
  ANYKERNEL_BRANCH: "lime"
  
  # Telegram Encrypted Secrets
  TG_TOKEN: "ENCRYPTED[d9185ab32fea60b59b9caac7865c156001691d0c6c87c825c32a3db288ed566a8ac07cfe7ff445fb2c0e61f57c06b486]"
  TG_CHAT_ID: "ENCRYPTED[d1175d4be5c2ebcb2ce25c91ec7c71abeb738d22d563c4fc0afdb9f528c2d6997b98e29309468198038eb159cc709e91]"

  # Toolchain Configuration
  USE_CLANG: "aosp" # "aosp" or "greenforce"
  CLANG_ROOTDIR: "/tmp/cirrus-ci-build/clang"
  AOSP_CLANG_URL: "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/clang-r574158.tar.gz"
  GREENFORCE_CLANG_URL: "https://github.com/greenforce-project/greenforce_clang/releases/download/20260103/gf-clang-22.0.0-20260103.tar.gz"

  # Kernel Build Configuration
  TYPE_IMAGE: "Image.gz"
  BUILD_DTBO: "true"
  DISABLE_LOCALVERSIO_ST: "true"
  INCLUDE_DTB: "true"
  DTB_PATH: "arch/arm64/boot/dts/vendor/qcom/bengal.dtb"

  # Kernel SU configuration
  KERNELSU: "true"
  KERNELSU_TYPE: "rksu"
  KERNELSU_BRANCH: "main"
  KPM_PATCH: "false"
  KPM_VERSION: "0.12.0"

  # Build optimization
  BUILD_OPTIONS: "-j8"
  CCACHE: "false"
  CCACHE_DIR: "/tmp/ccache"
  CCACHE_MAXSIZE: "2G"
  CCACHE_COMPRESS: "true"
  
  # New: Enhanced logging and debugging
  DEBUG_MODE: "false"
  KEEP_BUILD_LOGS: "false"

task:
  name: "Kernel Build"
  timeout_in: 3h
  container:
    image: mhmmdfdlyas/dockerfile:k-ubuntu
    cpu: 8
    memory: 32G

  # Cache configuration
  ccache_cache:
    folder: /tmp/ccache
    fingerprint_script: 
      - cat .cirrus.yml
      - echo "$AOSP_CLANG_URL"
      - echo "$GREENFORCE_CLANG_URL"
      - echo "$DEVICE_DEFCONFIG"

  update_script:
    - apt-get update
    - apt-get install -y aria2 ccache libssl-dev ncurses-dev flex bison cpio xz-utils locales libtinfo5
    - echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen && /usr/sbin/locale-gen
    - ln -snf /usr/share/zoneinfo/"$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
    - apt-get clean

  setup_script:
    - mkdir -p /tmp/ccache
    - ccache -M $CCACHE_MAXSIZE
    - ccache -z

  sync_script:
    - chmod +x download.sh
    - ./download.sh

  build_script:
    - chmod +x build.sh
    - ./build.sh

  cleanup_script:
    - chmod +x done.sh
    - ./done.sh
