env:
  TZ: Asia/Jakarta
  DEVICE_CODENAME: chime
  BUILD_USER: admin
  BUILD_HOST: mrtproject
  KERNEL_SOURCE: https://github.com/MRT-project/android_kernel_xiaomi_sm6115
  KERNEL_BRANCH: 13.0.0-perf
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
  ANYKERNEL: https://github.com/greenforce-project/AnyKernel3
  TG_TOKEN: ENCRYPTED[b14a58bf7498c8dbb829ea846623a88dc20d438fb6b12889ff25212fc5c20d8bc9c028e079bbaf097f1f549d1d4a0572]
  TG_CHAT_ID: ENCRYPTED[d1175d4be5c2ebcb2ce25c91ec7c71abeb738d22d563c4fc0afdb9f528c2d6997b98e29309468198038eb159cc709e91]

task:
  name: "Kernel Build.."
  timeout_in: 3h
  stateful: true
  container:
    image: mhmmdfdlyas/dockerfile:k-ubuntu
    cpu: 8
    memory: 32G

  sync_script:
    - ./download.sh

  build_kernel_script:
    - ./build.sh
    - ./done.sh
