env:
  TZ: Asia/Jakarta
  CCACHE: true
  CCACHE_DIR: /tmp/ccache
  CCACHE_MAXSIZE: 10G
  CCACHE_COMPRESS: true

task:
  name: "Kernel Build"
  timeout_in: 3h
  container:
    image: mhmmdfdlyas/dockerfile:r-ubuntu
    cpu: 8
    memory: 32G

  # Cache configuration
  ccache_cache:
    folder: /tmp/ccache
    fingerprint_script: cat .cirrus.yml > /dev/null

  update_script:
    - apt-get update && apt-get upgrade -y
    - apt-get install -y aria2 ccache libssl-dev ncurses-dev flex bison

  setup_script:
    - mkdir -p /tmp/ccache
    - ccache -M 2G

  sync_script:
    - ./sync.sh

  build_script:
    - ./building.sh
