env:
  TZ: Asia/Jakarta
  CCACHE: true
  CCACHE_DIR: /tmp/ccache
  CCACHE_MAXSIZE: 10G
  CCACHE_COMPRESS: true
  TG_TOKEN: ENCRYPTED[d9185ab32fea60b59b9caac7865c156001691d0c6c87c825c32a3db288ed566a8ac07cfe7ff445fb2c0e61f57c06b486]
  TG_CHAT_ID: ENCRYPTED[d1175d4be5c2ebcb2ce25c91ec7c71abeb738d22d563c4fc0afdb9f528c2d6997b98e29309468198038eb159cc709e91]
  

task:
  name: "Kernel Build"
  timeout_in: 3h
  container:
    image: mhmmdfdlyas/dockerfile:r-ubuntu
    cpu: 8
    memory: 32G

  # Cache configuration
  ccache_cache:
    folder: /tmp/ccache
    fingerprint_script: cat .cirrus.yml > /dev/null

  update_script:
    - apt-get update -y
    - apt-get install -y aria2 ccache libssl-dev ncurses-dev flex bison

  setup_script:
    - mkdir -p /tmp/ccache
    - ccache -M 2G

  sync_script:
    - ./sync.sh

  build_script:
    - ./building.sh
